name: Build and Deploy Multiplication App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore Test/Multiplication/Multiplication.csproj

    - name: Build
      run: dotnet build Test/Multiplication/Multiplication.csproj --configuration Release

    - name: Publish
      run: dotnet publish Test/Multiplication/Multiplication.csproj --configuration Release --output ./publish

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'multiplication11-eubscnd2f7drg9dg'  # Your Azure App Name
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
        package: './publish'
